repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        entry: ruff
        args: ["check", "--fix"]
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff
        args: ["format"]
        language: system
        types: [python]
      - id: yamllint
        name: yamllint
        entry: yamllint
        args: ["-s"]
        language: system
        types: [yaml]
